name: Build and Create Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x86_64
          - os: windows-latest
            label: windows
            python: "3.10"

          # Linux x86_64
          - os: ubuntu-22.04
            label: linux-x86_64
            python: "3.10"

          # Linux ARM64
          - os: ubuntu-22.04-arm
            label: linux-arm64
            python: "3.10"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build GUI
        run: |
          pyinstaller --onefile --add-data "assets${{ runner.os == 'Windows' && ';' || ':' }}assets" PPA.py --name PPA-gui

      - name: Build CLI
        run: |
          pyinstaller --onefile PPA-cli.py --name PPA-cli


      - name: Rename GUI artifacts
        run: |
          cp dist/PPA-gui${{ runner.os == 'Windows' && '.exe' || '' }} dist/PPA-gui-${{ matrix.label }}${{ runner.os == 'Windows' && '.exe' || '' }}


      - name: Rename CLI artifacts
        run: |
          cp dist/PPA-cli${{ runner.os == 'Windows' && '.exe' || '' }} dist/PPA-cli-${{ matrix.label }}${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/PPA-gui-${{ matrix.label }}${{ runner.os == 'Windows' && '.exe' || '' }}
          name: PPA-gui-${{ matrix.label }}
          retention-days: 5

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/PPA-cli-${{ matrix.label }}${{ runner.os == 'Windows' && '.exe' || '' }}
          name: PPA-cli-${{ matrix.label }}
          retention-days: 5

  create_release:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts # All from this workflow
        uses: actions/download-artifact@v4
        with:
          path: release_files
          merge-multiple: true # Puts them all flat in the 'release_files'

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ""
          tag_name: ${{ github.ref_name }}
          name: "PhotoPolarAlign ${{ github.ref_name }}"
          files: release_files/*
